RGBLIGHT_ENABLE    = no
RGB_MATRIX_ENABLE  = WS2812
MOUSEKEY_ENABLE    = no
NKRO_ENABLE        = yes
OLED_DRIVER_ENABLE = yes
EXTRAKEY_ENABLE    = no
TAP_DANCE_ENABLE   = yes
AUDIO_ENABLE	   = no

#BOOTLOADER         = caterina
#SPLIT_KEYBOARD	   = yes
CONSOLE_ENABLE 	   = yes
